name: d2l
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - asttokens=3.0.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - decorator=5.2.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.1.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang-cpp21.1=21.1.4
  - libclang13=21.1.4
  - libcups=2.3.3
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm21=21.1.4
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=18.0
  - libsqlite=3.50.4
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.12.2
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=2.3.4
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - prompt-toolkit=3.0.52
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyside6=6.9.3
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.9.3
  - readline=8.2
  - requests=2.32.5
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wayland=1.24.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - filelock==3.19.1
      - fsspec==2025.9.0
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.5
      - nvidia-cublas==13.0.0.19
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufile==1.15.0.42
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - sympy==1.14.0
      - torch==2.9.1+cu130
      - torchvision==0.24.1+cu130
      - tqdm==4.67.1
      - triton==3.5.1
prefix: /home/lanxiukai/mambaforge/envs/d2l
